### PR TITLE
Bunch of smaller fixes

### LINKED ISSUE #1785: Ensure "Use source for symbol files" is true for Unity projects
Read only packages are compiled by Unity and added as references to generated projects. As long as Unity generates PDB files, and the "Use sources from symbol files" option is checked, Rider will be able to navigate from an indexed compiled symbol to the source file. If this option is unchecked, we get decompiled source instead. 

We should check that the "Use sources from symbol files" option is checked for Unity projects. I think it would be ok to enable it automatically - it's set to true in the default settings, and makes sense to enforce for Unity projects. The alternative would be to show a notification to re-enable the setting.

### PR DESCRIPTION
**Pull request by citizenmatt**
- [x] Add automatic settings to ensure that navigation to source from PDB is enabled. Ensures navigation in packages goes to source files, not decompiled code. Fixes #1785 
- [x] Add automatic settings to always show implicit conversion hints, e.g. `Vector3` implicitly converted to `Vector2` loses information. These hints are push-to-hint by default
- [x] Fix some annotations - #145, #1619 
- [x] Remove checks for ECS injected fields, which are no longer used
- [x] Mark ComponentSystemBase and derived types in use - [RIDER-46106](https://youtrack.jetbrains.com/issue/RIDER-46106), #1895
- [x] Fix `[Range]` attribute analysis - #1788 
- [x] Fix presentation mode font size handling for Unity log tool window
- [x] Fix incorrect redundant `[SerializeField]` attributes on fields of type `T` - #1885 
- [x] Fix fields with `[SerializeReference]` not being recognised as serialised field - #1340 
- [x] Fix `Dictionary<TKey, TValue>` being treated as a serialisable field - #1776 
- [x] Fix incorrect redundant serialisation warnings for types such as `Vector2Int`, `BoundsInt`, etc. - see [RIDER-18729](https://youtrack.jetbrains.com/issue/RIDER-18729)
- [x] Fix `sfield` and `sprop` live templates missing in `[Serializable]` types - #1662 
- [x] Fix `.asmdef` file template missing under `Packages` folders - #780

### CODE REVIEW

File: resharper/resharper-unity/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressor.cs [hunk 1]
```diff
@@ -74,14 +70,15 @@ public bool SuppressUsageInspectionsOnElement(IDeclaredElement element, out Impl
                         return false;
                     }
 
-                    if (IsEventHandler(unityApi, method) || IsRequiredSignatureMethod(method))
+                    if (IsEventHandler(unityApi, method) || IsRequiredSignatureMethod(method) ||
+                        IsImplicitlyUsedInterfaceMethod(method))
```
Comment (krasnotsvetov) [inline resharper/resharper-unity/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressor.cs:74]: Is it impossible to have implicitly used interface method which is not event function?

File: resharper/resharper-unity/src/CSharp/Feature/Services/TypeConversionHints/CSharpTypeConversionHintsSettingsProvider.cs [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+        private readonly ISettingsSchema mySettingsSchema;
+        private readonly ILogger myLogger;
+
+        public CSharpTypeConversionHintsSettingsProvider(ISettingsSchema settingsSchema, ILogger logger)
+        {
+            mySettingsSchema = settingsSchema;
+            myLogger = logger;
+        }
+
+        public void InitialiseSolutionSettings(ISettingsStorageMountPoint mountPoint)
```
Comment (krasnotsvetov) [inline resharper/resharper-unity/src/CSharp/Feature/Services/TypeConversionHints/CSharpTypeConversionHintsSettingsProvider.cs:23]: I am not sure, that we should change default Rider behaviour for hints, at least in latest EAP

File: rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt [hunk 3]
```diff
@@ -163,7 +166,7 @@ class UnityLogPanelView(lifetime: Lifetime, project: Project, private val logMod
     @Suppress("SpellCheckingInspection")
     private val listPanel = JPanel(MigLayout("ins 0, gap 0, flowy, novisualpadding, fill", "", "[][min!]")).apply {
         add(JBScrollPane(eventList).apply { horizontalScrollBarPolicy = ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER }, "grow, wmin 0")
-        add(searchTextField, "growx")
+        add(searchTextField, "grow")
```
Comment (krasnotsvetov) [inline rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt:169]: cc @van800

File: resharper/resharper-unity/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProvider.cs [hunk 4]
```diff
@@ -183,22 +174,123 @@ public ICollection<IAttributeInstance> GetSpecialAttributeInstances(IClrDeclared
...
+                    {
+                        if (myCtorArguments.Length == 0)
+                        {
+                            if (constructor.IsDefault) return constructor;
+
+                            continue;
+                        }
+
+                        var parameters = constructor.Parameters;
+                        if (parameters.Count == myCtorArguments.Length)
```
Comment (krasnotsvetov) [inline resharper/resharper-unity/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProvider.cs:261]: that approach will not work for attributes with default parameters or if attribute arguments will be passed by name(order could be changed)

Comment (krasnotsvetov) [reply resharper/resharper-unity/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProvider.cs:261]: I am not sure is it relevant to usage of your class or not

**Review by krasnotsvetov — APPROVED** [review]

File: resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Scope/UnityProjectVersionScopeProvider.cs [hunk 5]
```diff
@@ -20,28 +19,22 @@ public IEnumerable<ITemplateScopePoint> ProvideScopePoints(TemplateAcceptanceCon
                 yield break;
 
             var project = context.GetProject();
-            if (project != null && !project.IsUnityProject())
-                yield break;
+            var version = project != null
+                ? context.Solution.GetComponent<UnityVersion>().GetActualVersion(project)
+                : context.Solution.GetComponent<UnityVersion>().ActualVersionForSolution.Value;
```
Comment (van800) [inline resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Scope/UnityProjectVersionScopeProvider.cs:24]: I would rather check ActualVersionForSolution first.

            var version = project != null
                ? context.Solution.GetComponent<UnityVersion>().ActualVersionForSolution.Value;
                : context.Solution.GetComponent<UnityVersion>().GetActualVersion(project)

File: rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt (hunk 3 above)
Comment (van800) [reply rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt:169]: I am not an expert in that UI tweaks, but I tried the branch and this change doesn't brake the layout of UnityLogView.

@citizenmatt what this change does?

Comment (citizenmatt) [reply rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt:169]: It means the search field will grow both in x and y. So it was stretching to fit horizontally, but didn't grow vertically, so if there was a larger font, the height would be wrong.

File: resharper/resharper-unity/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressor.cs (hunk 1 above)
Comment (citizenmatt) [reply resharper/resharper-unity/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressor.cs:74]: Yes. I don't think there was any reason to order the `IsImplicitlyUsedInterfaceMethod` before this check.

File: resharper/resharper-unity/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProvider.cs (hunk 4 above)
Comment (citizenmatt) [reply resharper/resharper-unity/src/CSharp/Psi/CodeAnnotations/CustomCodeAnnotationProvider.cs:261]: This doesn't affect usage. The attribute instance I'm creating is simple, only intended to be used to create a small number of annotation attributes and uses an array of values to find a constructor, based on correct order and type. So it's not intended to be used with default or named parameters.

File: resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Scope/UnityProjectVersionScopeProvider.cs (hunk 5 above)
Comment (citizenmatt) [reply resharper/resharper-unity/src/CSharp/Feature/Services/LiveTemplates/Scope/UnityProjectVersionScopeProvider.cs:24]: I think it's fine for now. We're using `GetActualVersion(IProject)` in lots of places, including `UnityApi` for completion, usage suppression and so on. I'm up for reviewing `UnityVersion` usage in 211 though - it might be worth removing the `IProject` API completely.

**Review by van800 — APPROVED** [review]

File: resharper/resharper-unity/src/CSharp/Feature/Services/TypeConversionHints/CSharpTypeConversionHintsSettingsProvider.cs (hunk 2 above)
Comment (citizenmatt) [reply resharper/resharper-unity/src/CSharp/Feature/Services/TypeConversionHints/CSharpTypeConversionHintsSettingsProvider.cs:23]: This is the change I'm least sure of. I would much rather Rider showed implicit conversion hints by default, but it doesn't - they're hidden. 

My argument for doing it is that implicit type conversion hints are massively useful for highlighting issues such as possible data loss converting `Vector2` to `Vector3` and vice versa. These currently happen silently, and could easily be bugs, but we don't know intent enough to be able to show an inspection highlight. Showing a conversion hint is a great way to show this.

The setting can be changed and overridden by the user, so it can still be disabled.
