### PR TITLE
fix docs being incorrect about EditorWindow.OnProjectChange

### LINKED ISSUE #679: OnProjectChange event of Unity's EditorWindow class is recognized as "never used" in last version. It was working fine before.
OnProjectChange event of Unity's EditorWindow class is recognized as "never used" in last version. It was working fine before.

### PR DESCRIPTION
**Pull request by IvanPashchenko**
fix ApiParser to work with hub on windows
fixes #679

### CODE REVIEW

File: apiParser/src/Program.cs [hunk 1]
```diff
@@ -34,6 +34,7 @@ public static class Program
```
Comment (IvanPashchenko) [inline apiParser/src/Program.cs]: @citizenmatt should I do something with that list?

Comment (citizenmatt) [reply apiParser/src/Program.cs]: Nah. It's useful if you need to completely recreate the docs list, but you need ALL of those folders installed somewhere, and that's several gigabytes of html. It's much easier just to incrementally update it by comparing the existing API list against a new docs folder. Leave this around if we ever have a need to completely rebuild. I know we probably won't, and it's in source control and everything, but, I can't get too worked up about an internal tool :)

File: apiParser/src/Program.cs [hunk 2]
```diff
@@ -228,6 +231,15 @@ private static void FixDataFromIncorrectDocs(UnityApi unityApi)
                 foreach (var function in type.FindEventFunctions("OnAssignMaterialModel"))
                     function.SetReturnType(new ApiType("UnityEngine.Material"));
             }
+
```
[the remark this answers is not in the document]
Comment (IvanPashchenko) [reply apiParser/src/Program.cs]: done
