### PR TITLE
Fix exception for file: and git based packages

### LINKED ISSUE #1095: Unity Explorer disappeared
image
Where item "Unity" ?

Version 2019.1.0.17

### PR DESCRIPTION
**Pull request by citizenmatt**
This PR will:

- [x] Correctly handle local `file:` and git based packages in Unity Explorer
- [x] Unresolved packages will no longer crash the Unity Explorer, but be displayed as unresolved nodes
- [x] Simplify sorting nodes in the Unity Explorer tree

Fixes #1095, fixes [RIDER-25971](https://youtrack.jetbrains.com/issue/RIDER-25971)

### CODE REVIEW

File: rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/AssetsRoot.kt [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+        val visitor = object : ProjectModelNodeVisitor() {
+            override fun visitReference(node: ProjectModelNode): Result {
+                if (node.isAssemblyReference()) {
+                    val keys = referenceNames.getOrCreate(node.name) { _ -> arrayListOf() }
+                    keys.add(node.key)
+                }
+                return Result.Stop
+            }
+        }
+        visitor.visit(project!!)
```
Comment (van800) [inline rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/AssetsRoot.kt]: Could this ever be called when project is null?

Comment (citizenmatt) [reply rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/AssetsRoot.kt]: No, we only ever create the Unity explorer and nodes when we have a project.
